[font]
size = 12.0
normal.family = "JetBrainsMonoNerdFont"
# normal.family = "JetBrains Mono"
# bold.family = "JetBrains Mono"
# italic.family = "JetBrains Mono"
# bold_italic.family = "JetBrains Mono"
