#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &
pgrep -x picom > /dev/null || picom --inactive-opacity 0.8 --active-opacity 0.96 &
pgrep -x xsettingsd > /dev/null || xsettingsd -c ~/.config/xsettingsd/xsettingsd.conf &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color "#e69875"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a crello state=floating
bspc rule -a float-term state=floating
bspc rule -a "cinnamon-settings sound" state=floating
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a Blueman-manager state=floating
# discover window class : xprop | grep WM_CLASS

setxkbmap -option ctrl:nocaps
feh --bg-fill ~/Pictures/wallpepers/reze_everforest.png
redshift -x
redshift -O 3000 &

