#!/usr/bin/env bash
# get volume
# :properties:
# :header-args: :tangle scripts/get_vol :comments org :shebang #!/usr/bin/env bash
# :end:

# .__                        
# |__| ______  _  ____  _  __
# |  |/ __ \ \/ \/ /\ \/ \/ /
# |  \  ___/\     /  \     / 
# |__|\___  >\/\_/    \/\_/  
#         \/                 

#   Made by Italo Guedes (Github @italoguedess) as
#   a part of italOS (Github @italoguedess/italOS).

wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2 * 100}'
