#!/usr/bin/env bash
# menu_launcher
# :properties:
# :header-args: :tangle scripts/menu_launcher :comments org :shebang #!/usr/bin/env bash
# :end:

# .__                        
# |__| ______  _  ____  _  __
# |  |/ __ \ \/ \/ /\ \/ \/ /
# |  \  ___/\     /  \     / 
# |__|\___  >\/\_/    \/\_/  
#         \/                 

#   Made by Italo Guedes (Github @italoguedess) as
#   a part of italOS (Github @italoguedess/italOS).

hyprctl dispatch exec kitty
