# Configure our fonts.
Gtk/CursorThemeName "Banana"
Xft/Antialias 1
Xft/HintStyle "hintfull"
Xft/Hinting 1
Xft/RGBA "none"
Xft/lcdfilter "none"
Net/ThemeName "Jasper-Orange-Dark"
Net/IconThemeName "Papirus-Dark"

